model:
    cls: DiT_B_4

dataset:
    root: /home/emil/KTH/Adv. Deep Learning/Project/DD2610-Project-Mean-Flow/meanflow-jax/data/dummy_data 

training:
    log_per_step: 100
    checkpoint_per_epoch: 10

    num_epochs: 240
    learning_rate: 0.0001
    batch_size: 128
    adam_b2: 0.95
    ema_type: 'const'

    sample_on_training: True
    sample_per_epoch: 10
    fid_per_epoch: 10

    seed: 42

fid:
    device_batch_size: 2  # Reduced for local GPU (was 10)
    num_samples: 50000  # Reduced for faster local testing (was 50000)
    cache_ref: /home/emil/KTH/Adv. Deep Learning/Project/DD2610-Project-Mean-Flow/meanflow-jax/imagenet_fid_stats.npz
    on_training: True

sampling:
    num_steps: 1

# Load checkpoints for eval or resuming training.
load_from: /home/emil/KTH/Adv. Deep Learning/Project/DD2610-Project-Mean-Flow/meanflow-jax/checkpoints/mf_b4/checkpoint_1200960 #/home/jupyter/DD2610-Project-Mean-Flow/meanflow-jax/checkpoints/mf_b4/checkpoint_1200960

eval_only: True
